### ISSUE TITLE
Django 1.11 support?

### ISSUE THREAD

**Issue by brylie** [rbarrois/django-factory_boy#5]
The Cookiecutter Django project depends on this package. Currently, Cookiecutter Django is pinned to Django 1.10.x, based on an [issue to check for 1.11.x support in project dependencies](https://github.com/pydanny/cookiecutter-django/issues/1111). 

Does the django-factory_boy package support Django 1.11?

**Comment by rbarrois** [comment]
If might not right now, but there shouldn't be any issue migrating. Would you have the time to submit such a pull request?

I'm not sure I'd be able to handle that myself before a couple of weeks :/

**Comment by ThibaultLemaire** [comment]
I don't know exactly what you are talking about, or if this still applies, but we're currently using django-factory_boy with Django 1.11.15 and it works perfectly.

**Comment by brylie** [comment]
Looks like it was [marked as resolved in 2017](https://github.com/pydanny/cookiecutter-django/issues/1111#issuecomment-326314963).
